### ISSUE TITLE
When will the complete code be available?

### ISSUE THREAD

**Issue by RanHao-cq** [JMoonr/LATR#1]
Hello. I am very impressed by your work and I would like to use your method. Could you please share the code or update it on GitHub? Thank you very much.

**Comment by BroderickHigby** [comment]
upvoting this

**Comment by JMoonr** [comment]
Thank you for your interest in our work and for your kind words. We are in the process of finalizing the release code and will be sharing the model and test code before the main conference. The training code is scheduled for release before November. Stay tuned for updates, and thank you for your patience!

**Comment by daishiqiang123** [comment]
Thank you very much for your work. May I ask if there will be any open source code in the future? If so, thank you very much

**Comment by JMoonr** [comment]
Thanks for your patience!  we have updated our code. Feel free to reopen if you have any problems.
