### ISSUE TITLE
camera coordinate system definition?

### ISSUE THREAD

**Issue by ailihong** [JMoonr/LATR#15]
Thank you for the author's great engineering work and the open-source code. 
I have a quick question: could you clarify the definition of the camera coordinate system in openlane or latr (before transformation in data/Load_Data.py)? Is it based on the Apollo camera coordinate system, the WOD camera coordinate system, or something else?

**Comment by JMoonr** [comment]
[OpenLane coordinate system](https://github.com/OpenDriveLab/OpenLane/blob/main/data/Coordinate_Sys.md) aligns with WOD. For the openlane lane label details, you can refer to the [OpenLane official doc](https://github.com/OpenDriveLab/OpenLane/blob/main/anno_criterion/Lane/README.md).

**Comment by JMoonr** [comment]
Closing this issue due to lack of response. Feel free to reopen if needed.

**Comment by ailihong** [comment]
Hello, thank you for your response. Have you tested this on other datasets? I tested it on our proprietary data, and the output for lane lines doesn't seem quite normal. I'm unsure if it's a model generalization issue or a problem with my own code.
