### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by javierpastorfernandez** [JMoonr/LATR#27]
Good morning, 
Could you provide under which license is this work released?
Can be used openly for research and / or commercial purposes?

Thank you in advance,

**Comment by JMoonr** [comment]
Thank you for your interest in our work and for reaching out with your inquiry.  Our work is released under the **MIT LICENSE**. Check [this commit](https://github.com/JMoonr/LATR/commit/3c72bea38f3298a17ff2e21572b14292f8f84142) for the license update :)
