### ISSUE TITLE
Instruction exception

### ISSUE THREAD

**Issue by AZKvgkv** [JMoonr/LATR#30]
# Data Preparation

## OpenLane

Follow [OpenLane](https://github.com/OpenDriveLab/PersFormer_3DLane#dataset) to download dataset and then link it under `data` directory.

```bash
cd data && makir openlane && cd openlane
ln -s ${OPENLANE_PATH}/images .
ln -s ${OPENLANE_PATH}/lane3d_1000 .
```

The first instruction should be 
```bash
cd data && mkdir openlane && cd openlane
```

**Comment by usst-st** [comment]
[LATR](https://github.com/JMoonr/LATR/tree/3c72bea38f3298a17ff2e21572b14292f8f84142)/[docs](https://github.com/JMoonr/LATR/tree/3c72bea38f3298a17ff2e21572b14292f8f84142/docs)
/train_eval.md
## Evaluation
- Apollo
	- Visual Variations
	`CUDA_VISIBLE_DEVICES='0,1,2,3' python -m torch.distributed.launch --master_port=29284 --nproc_per_node 4 main.py --config config/release_iccv/apollo_standard.py --cfg-options evaluate=true eval_ckpt=pretrained_models/apollo_illu.pth`
	should be `CUDA_VISIBLE_DEVICES='0,1,2,3' python -m torch.distributed.launch --master_port=29284 --nproc_per_node 4 main.py --config config/release_iccv/apollo_illu.py --cfg-options evaluate=true eval_ckpt=pretrained_models/apollo_illu.pth`
