### ISSUE TITLE
query = torch.zeros_like(query_embeds) ？？

### ISSUE THREAD

**Issue by Hanson0910** [JMoonr/LATR#5]
感谢大佬的分享，models/latr_head.py代码里面每次都把query设置为0=》query = torch.zeros_like(query_embeds)。这步操作确实看不懂，大佬能否解答一下。

**Comment by JMoonr** [comment]
This is a common choice in transformer-based detectors, like [DETR](https://github.com/facebookresearch/detr/blob/3af9fa878e73b6894ce3596450a8d9b89d918ca9/models/transformer.py#L55) and [PETR](https://github.com/megvii-research/PETR/blob/f7525f93467a33707ef401c587a52d5e7b34de74/projects/mmdet3d_plugin/models/utils/petr_transformer.py#L96), please kindly refer to the provided links of their source code and papers.
