### ISSUE TITLE
mmcv 1.5.0 and mmdet3d 1.0.0rc3 incompatible

### ISSUE THREAD

**Issue by qiang-sean-liu** [JMoonr/LATR#6]
mmdet3d==1.0.0rc3 requires mmcv>=2.0.0rc4. But mmcv>=2.0.0rc4 will cause running errors. How to deal with this?

**Comment by JMoonr** [comment]
[mmdet3d==1.0.0rc3](https://github.com/open-mmlab/mmdetection3d/blob/bb204696c19ded90121caea82e34fa3ff0bd131f/mmdet3d/__init__.py#L22) requires 1.4.8 <= mmcv < 1.6.0, please make sure your mmdet3d is 1.0.0rc3.

**Comment by JMoonr** [comment]
Closing due to lack of feedback. Feel free to reopen if needed. Thanks!
